### PR TITLE
Svelte

### PR DESCRIPTION
**Pull request by FunctionalMetatable**
svelte website yay

### CODE REVIEW

**Comment by micahlt** [comment]
Woah yikes, might want to ask the maintainer of this repo before making a major structural change - I personally don't know Svelte so I can't review this PR.

**Comment by ninjamar** [comment]
How would I test this out locally? I don't know svelte. Could you explain the files to me?

**Comment by FunctionalMetatable** [comment]
> How would I test this out locally?

Install Node.js (and if you don't have yarn globally installed run `npm install -g yarn`)

Install Dependencies (`yarn`)
Run in development, show website at localhost:3000 (`yarn dev`)


> Could you explain the files to me?

just read kit.svelte.dev





> Why is svelte better than what we have now?

everybody is moving their websites to svelte

**Comment by ninjamar** [comment]
> everybody is moving their websites to svelte
why is svelte better than what we have now?

**Comment by micahlt** [comment]
> > Why is svelte better than what we have now?
> 
> everybody is moving their websites to svelte
> 

Just because "everyone is doing it" doesn't mean it's the best for _every project_, especially not one as simple as this.

**Comment by FunctionalMetatable** [comment]
> > > Why is svelte better than what we have now?
> > 
> > 
> > everybody is moving their websites to svelte
> 
> Just because "everyone is doing it" doesn't mean it's the best for _every project_, especially not one as simple as this. To clarify, adding dependencies and a build process to a very, very simple static website is more trouble than it's worth.

hmm good point

**Comment by MystPi** [comment]
> > > Why is svelte better than what we have now?
> > 
> > 
> > everybody is moving their websites to svelte
> 
> Just because "everyone is doing it" doesn't mean it's the best for _every project_, especially not one as simple as this. To clarify, adding dependencies and a build process to a very, very simple static website is more trouble than it's worth.

I agree.

**Pull request closed without merging**
