### PR TITLE
Added github actions for studio curators

### PR DESCRIPTION
**Pull request by ninjamar**
I added a github action which gets the data from the scratch api about the studio curators. The output is stored in curators.json. The script runs at UTC 12:00. Can someone make a js script to parse /curators.json? Also should I move the python script to /.github/workflows/?

### CODE REVIEW

**Comment by MystPi** [comment]
> > > > I'm sorry, but why is this needed? I can change the members page to show more data if you want.
> > > > Plus, I don't understand GitHub actions lol.
> > > 
> > > 
> > > I think this will update the curators list every time someone makes a commit. That way we don't have to do the work of updating the curator list a bunch
> > 
> > 
> > You don't understand, it already automatically updates. Check the script.js script.
> 
> That makes requests to the Github API not the Scratch curators list; besides it only seems to show you, me, and dhuls public members of the organization as members.

But I thought this site was for the organization, as there is already an advanced topics site for the studio.

**Comment by gosoccerboy5** [comment]
> But I thought this site was for the organization, as there is already an advanced topics site for the studio.

ask ninjamar about their motives. I'm not the one with the idea to have the list of curators, I'm just discussing the idea.

**Comment by ninjamar** [comment]
> This looks cool, however this site is for the GitHub organization, not the studio. (There is already a site for the studio.)
> 
> Another thing is that this could easily be done with JavaScript on the site itself without having to rely on the list created by the action. 
> 
> All in all, I'm going to disapprove these changes as it would add an extra layer of complexity without making the site significantly better.
> 
> Of course this is just my opinion and I don't really understand GitHub actions very well, so the 'extra layer of complexity' could just from my non-understanding of GH actions.

If js makes requests to the scratch api from github pages, won't cors block the requests? The github action I made isn't that complex. It runs curators.py and then uploads the result to the github repo

**Comment by ninjamar** [comment]
Should I move curators.py into /.github/workflows/scripts/?

**Comment by MystPi** [comment]
> Should I move curators.py into /.github/workflows/scripts/?

Nah, I already updated the page. It would mean another PR.

**Pull request merged**
