### PR TITLE
😎 Dark mode and cool menu hover effect

### PR DESCRIPTION
**Pull request by micahlt**
This PR changes the site to a default dark theme that is easier to read.  It also adds a "terminal cursor" effect when menu items are hovered upon.

### CODE REVIEW

**Comment by micahlt** [comment]
The preferable solution for this problem would be to write some JS that takes into account the `prefers-color-scheme` media query and bases the theme on that.  The downside is that any Linux users will simply have to deal with light theme, which is why I made dark the default.

**Comment by ninjamar** [comment]
> The preferable solution for this problem would be to write some JS that takes into account the `prefers-color-scheme` media query and bases the theme on that. The downside is that any Linux users will simply have to deal with light theme, which is why I made dark the default.

We could use cookies to store the color scheme

**Comment by gosoccerboy5** [comment]
We should also probably change the cursor color when it's on light theme. At least on my machine, the light theme on Terminal is accompanied by a gray cursor

**Comment by ninjamar** [comment]
> > > The preferable solution for this problem would be to write some JS that takes into account the `prefers-color-scheme` media query and bases the theme on that. The downside is that any Linux users will simply have to deal with light theme, which is why I made dark the default.
> > 
> > 
> > We could use cookies to store the color scheme
> 
> Agreed, though `localStorage` would be preferable as it doesn't expire.

Good Idea

**Comment by micahlt** [comment]
I can make these changes 😊 Give me a few minutes.

**Comment by micahlt** [comment]
> > Also, could we add the hacktoberfest tag to this repo? That would definitely help with any participator's PR count.
> 
> Don't we have to sign up?

Nope, just add the tag to the repo!

**Comment by ninjamar** [comment]
> > > Also, could we add the hacktoberfest tag to this repo? That would definitely help with any participator's PR count.
> > 
> > 
> > Don't we have to sign up?
> 
> Nope, just add the tag to the repo!

done

**Comment by ninjamar** [comment]
Should we merge soon?

**Comment by MystPi** [comment]
> Should we merge soon?

@micahlt hasn't changed anything yet. (As far as his fork goes.)

**Comment by ninjamar** [comment]
> > Should we merge soon?
> 
> @micahlt hasn't changed anything yet. (As far as his fork goes.)

ok

**Comment by micahlt** [comment]
I'm almost done - I've made the CSS start using variables, but I just need to add a toggle and some logic to follow the `prefers-color-scheme` media query.

**Comment by micahlt** [comment]
> Ugh, `curators.json` always has such annoying conflicts!

Is there any reason we can't just gitignore it?

**Comment by ninjamar** [comment]
Can we not merge the .replit file?

**Comment by ninjamar** [comment]
> It's my bad - while trying to resolve the merge conflicts I accidentally merged the _PR_ into _`main`_ instead of _`main`_ into the _PR_.

I think the changes are fine

**Pull request merged**
